"""Convert data generated by text-render project"""
import argparse
import io
import os
from PIL import Image
from tqdm import tqdm


def get_img2label(syn_img_dir, label_file):
    f2label = []
    with open(label_file, encoding="utf-8") as f:
        for line in f:
            parts = line.strip().split(maxsplit=1)
            f2label.append((os.path.join(syn_img_dir, parts[0] + ".jpg"), parts[1]))

    return f2label


if __name__ == "__main__":
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument("images_dir")
    arg_parser.add_argument("label_file")
    arg_parser.add_argument("output_file")
    args = arg_parser.parse_args()

    syn_img_dir = args.images_dir
    label_file = args.label_file
    out_file = args.output_file  # 输出标注文件，每行一样本

    f2label = get_img2label(syn_img_dir, label_file)  # (文本图像文件,文本)元组列表

    max_width = 280  # 文本图像最大宽度
    min_width = 200  # 文本图像最小宽度
    filtered = 0
    count = 0
    with io.open(out_file, "w", encoding="utf-8") as meta_file_label:
        for e in tqdm(f2label):
            count += 1
            img = Image.open(e[0])
            width = img.size[0]
            label = e[1]
            if label[0] == " " or label[-1] == " ":  # filter image with text that begins or ends with space
                filtered += 1
                continue

            if min_width <= width <= max_width:  # filter image, the width of which is in the specified range
                meta_file_label.write(e[0] + "\t" + e[1] + "\n")
            else:
                filtered += 1

    print("Filtered: {}".format(filtered))
