from tensorflow_tts.processor.base_processor import BaseProcessor

from tensorflow_tts.processor.ljspeech import LJSpeechProcessor
from tensorflow_tts.processor.baker import BakerProcessor
from tensorflow_tts.processor.libritts import LibriTTSProcessor
from tensorflow_tts.processor.ljspeechu import LJSpeechUltimateProcessor